---
aws_vpc_name: ansible
aws_vpc_prefix: demo
aws_vpc_cidr_block: 10.0.0.0/16
aws_subnet_cidr: 10.0.1.0/24
aws_region: us-east-1
aws_vm_name: "{{ vm_name }}"
aws_vm_owner: "{{ vm_owner }}"
aws_blueprint: "{{ vm_blueprint }}"
# aws_image_filter: "{{ omit }}"
# aws_instance_size: "{{ omit }}"
# aws_image_architecture: "{{ omit }}"
# aws_image_owners: "{{ omit }} "
aws_userdata_template: default
aws_keypair_name: "{{ aws_vpc_name }}-{{ aws_vpc_prefix }}-demo-key"
aws_securitygroup_name: "{{ aws_vpc_name }}-{{ aws_vpc_prefix }}-sec-group"
aws_env_tag: prod
aws_purpose_tag: ansible_demo
aws_ansiblegroup_tag: cloud
aws_ec2_wait: true
aws_snapshots: {}

download_files: [{url: 'https://access.cdn.redhat.com/content/origin/files/sha256/0e/0eaee0fdcf6884e201b34d265c2614b6872b4e02b3f7fe3a6de3e88b3043c6ec/ansible-automation-platform-setup-2.4-13.tar.gz?user=c84227f2a18da30173574bd4f86d38ee&_auth_=1761703749_59cc4c518c0caf9df0318d85d45dd16e', dest: '/tmp/ansible-automation-platform-setup-2.4'}]
