---
- name: "Generate SSH key pair on Bastion"
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_private_path }}"
    type: "{{ ssh_key_type }}"
    size: "{{ ssh_key_size }}"
    state: present
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
    
- name: "Ensure work directory exists"
  ansible.builtin.file:
    path: "{{ install_path }}"
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: "Extract archive"
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ install_path }}"
    remote_src: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop: "{{ download_files }}"

- name: "Deploy Inventory File"
  ansible.builtin.template:
    src: "{{ inv24_src }}"
    dest: "{{ inv24_dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 600
    backup: no
    
- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  when: packages | length > 0
